import { BUILTIN_FUNCTION_CAPABILITIES } from './generated/function-capabilities.ts'

export type CapabilityFamily =
  | 'path'
  | 'indexer'
  | 'literal'
  | 'operator'
  | 'choice'
  | 'group'
  | 'union'
  | 'function-fixed'
  | 'function-input'
  | 'function-lambda'
  | 'syntax'
  | 'precedence'
  | 'variable'
  | 'reference'
  | 'host-context'

interface CapabilityFunctionSignature {
  input?: { types?: readonly string[] }
  result?: { types?: readonly string[]; single?: boolean }
}

type CapabilityFunction =
  | {
      expression: string
      signature?: CapabilityFunctionSignature
      criteria?: boolean
      envTypes?: Readonly<
        Record<string, { type: string | readonly string[]; collection?: boolean; targets?: string | readonly string[] }>
      >
    }
  | { overloads: readonly CapabilityFunction[] }

export interface CapabilityEntry {
  family: CapabilityFamily
  source: { corpusId: string } | { expression: string; corpusGap: string }
  input?: string
  context?: {
    variables?: Readonly<Record<string, { types?: readonly string[]; single?: boolean; targets?: readonly string[] }>>
    functions?: Readonly<Record<string, CapabilityFunction>>
  }
  typeContext?: object
  expectedType: string
  compositionType: string
  runtime: boolean
  analyzer: { types: readonly string[] | undefined; single: boolean | undefined }
  degradation: string
  composition: string
}

/** Baseline registry for the precise subset present before the full parser lands. */
export const INFERENCE_CAPABILITIES = {
  'path.resource-root': {
    family: 'path',
    source: { corpusId: 'official:r4:testBasics:testSimpleWithContext' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: 'Patient.nope',
    composition: 'Patient.name.given.first()',
  },
  'path.indexer': {
    family: 'indexer',
    source: { expression: 'Patient.name[0]', corpusGap: 'focused positive without a following equality' },
    expectedType: 'HumanName[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.HumanName'], single: true },
    degradation: 'Patient.name[0][bad]',
    composition: 'Patient.name[0].given',
  },
  'path.choice-stem': {
    family: 'choice',
    source: { expression: 'Observation.value', corpusGap: 'focused positive independent of an R5-only corpus case' },
    expectedType:
      "R4TypeOf['Quantity' | 'CodeableConcept' | 'string' | 'boolean' | 'integer' | 'Range' | 'Ratio' | 'SampledData' | 'time' | 'dateTime' | 'Period'][]",
    compositionType: 'number[]',
    runtime: true,
    analyzer: {
      types: [
        'FHIR.Quantity',
        'FHIR.CodeableConcept',
        'FHIR.string',
        'FHIR.boolean',
        'FHIR.integer',
        'FHIR.Range',
        'FHIR.Ratio',
        'FHIR.SampledData',
        'FHIR.time',
        'FHIR.dateTime',
        'FHIR.Period',
      ],
      single: true,
    },
    degradation: 'Observation.value.nope',
    composition: 'Observation.value.ofType(Quantity).value',
  },
  'group.navigation': {
    family: 'group',
    source: { expression: '(Patient.name).given', corpusGap: 'focused grouped-navigation composition' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '(Patient.name).given +',
    composition: '(Patient.name).given.first()',
  },
  'union.navigation': {
    family: 'union',
    source: { expression: '(Patient.name.given | Patient.name.family)', corpusGap: 'focused union result assertion' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '(Patient.name.given | Patient.nope)',
    composition: '(Patient.name.given | Patient.name.family).first()',
  },
  'function.fixed': {
    family: 'function-fixed',
    source: { corpusId: 'official:r4:testCount:testCount1' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: 'Patient.name.unknownFn()',
    composition: 'Patient.name.count().toString()',
  },
  'function.input': {
    family: 'function-input',
    source: { expression: 'Patient.name.first()', corpusGap: 'focused input-preserving function result' },
    expectedType: 'HumanName[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.HumanName'], single: true },
    degradation: 'Patient.name.first().nope',
    composition: 'Patient.name.first().given',
  },
  'function.select': {
    family: 'function-lambda',
    source: { corpusId: 'fhirpathjs:simple.yaml:22:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: 'Patient.name.select(nope)',
    composition: 'Patient.name.select(given).first()',
  },
  'variable.opaque-fixed': {
    family: 'variable',
    source: {
      expression: '%rowIndex.toString()',
      corpusGap: 'host variable declaration is absent from reference formats',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    context: { variables: { rowIndex: { types: ['System.Integer'], single: true } } },
    analyzer: { types: ['System.String'], single: true },
    degradation: '%rowIndex.nope',
    composition: '%rowIndex.toString().upper()',
  },
  'syntax.trivia': {
    family: 'syntax',
    source: {
      expression: 'Patient /* ignored . | ( ) */ . name',
      corpusGap: 'focused comment and whitespace tokenization case',
    },
    expectedType: 'HumanName[]',
    compositionType: 'HumanName[]',
    runtime: true,
    analyzer: { types: ['FHIR.HumanName'], single: false },
    degradation: 'Patient /* unterminated . name',
    composition: 'Patient /* ignored */ . name.first()',
  },
  'syntax.escaped-string': {
    family: 'syntax',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:1:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.String'], single: true },
    degradation: "'\\q'",
    composition: "'\\u00E9'.upper()",
  },
  'syntax.delimited-identifier': {
    family: 'syntax',
    source: { expression: 'Patient.`name`', corpusGap: 'focused known-model delimited identifier case' },
    expectedType: 'HumanName[]',
    compositionType: 'HumanName[]',
    runtime: true,
    analyzer: { types: ['FHIR.HumanName'], single: false },
    degradation: 'Patient.``',
    composition: 'Patient.`name`.first()',
  },
  'literal.empty': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:0:0' },
    expectedType: 'never[]',
    compositionType: 'boolean[]',
    runtime: true,
    analyzer: { types: [], single: true },
    degradation: '{',
    composition: '{}.exists()',
  },
  'literal.boolean': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:5.5_conversion.yaml:0:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'tru',
    composition: 'true.toString()',
  },
  'literal.integer': {
    family: 'literal',
    source: { expression: '7', corpusGap: 'focused integer literal without a unary operator' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '7 8',
    composition: '(7).toString()',
  },
  'literal.long': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:43:0' },
    expectedType: 'bigint[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Long'], single: true },
    degradation: '7LL',
    composition: '(-7L).toString()',
  },
  'literal.decimal': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:42:0' },
    expectedType: 'number[]',
    compositionType: 'number[]',
    runtime: true,
    analyzer: { types: ['System.Decimal'], single: true },
    degradation: '7.',
    composition: '(-7.3).round()',
  },
  'literal.string': {
    family: 'literal',
    source: { expression: "'plain'", corpusGap: 'focused string literal without escape syntax' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.String'], single: true },
    degradation: "'unterminated",
    composition: "'plain'.upper()",
  },
  'literal.date': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:20:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Date'], single: true },
    degradation: '@20',
    composition: '@2019.toString()',
  },
  'literal.date-time': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:31:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.DateTime'], single: true },
    degradation: '@2019-01-01T1',
    composition: '@2019-02-29T12:00.toString()',
  },
  'literal.time': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:35:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Time'], single: true },
    degradation: '@T1',
    composition: '@T14:30:00.toString()',
  },
  'literal.quantity': {
    family: 'literal',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:17:0' },
    expectedType: 'SystemQuantity[]',
    compositionType: 'number[]',
    runtime: true,
    analyzer: { types: ['System.Quantity'], single: true },
    degradation: '2 items',
    composition: "(2 'mo').value",
  },
  'operator.unary-plus': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:44:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: "+'text'",
    composition: '(+7).toString()',
  },
  'operator.unary-minus': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:4.1_literals.yaml:41:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: "-'text'",
    composition: '(-7).toString()',
  },
  'operator.multiply': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.6_math.yaml:1:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '2 *',
    composition: '(2 * 4).toString()',
  },
  'operator.divide': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.6_math.yaml:39:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Decimal'], single: true },
    degradation: '5 /',
    composition: '(5 / 2).toString()',
  },
  'operator.div': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:764:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '5 div',
    composition: '(5 div 2).toString()',
  },
  'operator.mod': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:769:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '5 mod',
    composition: '(5 mod 2).toString()',
  },
  'operator.add': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.6_math.yaml:85:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '2 +',
    composition: '(2 + 3).toString()',
  },
  'operator.subtract': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.6_math.yaml:129:0' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '5 -',
    composition: '(5 - 3).toString()',
  },
  'operator.concatenate': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.6_math.yaml:182:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.String'], single: true },
    degradation: "'a' &",
    composition: "('a' & 'b').upper()",
  },
  'operator.union': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:simple.yaml:21:0' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.String'], single: false },
    degradation: "'a' |",
    composition: "('a' | 'b').first()",
  },
  'operator.less-than': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.2_comparision.yaml:0:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 <',
    composition: '(1 < 2).toString()',
  },
  'operator.greater-than': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.2_comparision.yaml:11:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 >',
    composition: '(1 > 2).toString()',
  },
  'operator.less-or-equal': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.2_comparision.yaml:33:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 <=',
    composition: '(1 <= 2).toString()',
  },
  'operator.greater-or-equal': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.2_comparision.yaml:22:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 >=',
    composition: '(1 >= 2).toString()',
  },
  'operator.equal': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:442:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 =',
    composition: '(1 = 1).toString()',
  },
  'operator.equivalent': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:494:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 ~',
    composition: '(1 ~ 1).toString()',
  },
  'operator.not-equal': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:470:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 !=',
    composition: '(1 != 2).toString()',
  },
  'operator.not-equivalent': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:fhir-r4.yaml:518:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 !~',
    composition: '(1 !~ 2).toString()',
  },
  'operator.in': {
    family: 'operator',
    source: { corpusId: 'official:r5:testIn:testInEmptyCollection' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 in',
    composition: '(1 in (1 | 2)).toString()',
  },
  'operator.contains': {
    family: 'operator',
    source: { corpusId: 'official:r5:testContainsCollection:testContainsCollectionEmpty1' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '(1 | 2) contains',
    composition: '((1 | 2) contains 1).toString()',
  },
  'operator.and': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.5_boolean_logic.yaml:0:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true and',
    composition: '(true and false).toString()',
  },
  'operator.xor': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.5_boolean_logic.yaml:21:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true xor',
    composition: '(true xor false).toString()',
  },
  'operator.or': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.5_boolean_logic.yaml:10:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true or',
    composition: '(true or false).toString()',
  },
  'operator.implies': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.5_boolean_logic.yaml:32:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true implies',
    composition: '(true implies false).toString()',
  },
  'operator.is': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.3_types.yaml:3:0' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '5L is Nope',
    composition: '(5L is Long).toString()',
  },
  'operator.as': {
    family: 'operator',
    source: { corpusId: 'fhirpathjs:6.3_types.yaml:38:0' },
    expectedType: 'SystemQuantity[]',
    compositionType: 'number[]',
    runtime: true,
    analyzer: { types: ['System.Quantity'], single: true },
    degradation: '1 year as Nope',
    composition: '(1 year as System.Quantity).value',
  },
  'precedence.call-dot': {
    family: 'precedence',
    source: { expression: 'Patient.name.first().given', corpusGap: 'focused adjacent call/dot precedence case' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: 'Patient.name.first().given +',
    composition: 'Patient.name.first().given.first()',
  },
  'precedence.dot-index': {
    family: 'precedence',
    source: { expression: 'Patient.name[0].given', corpusGap: 'focused adjacent dot/index precedence case' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: 'Patient.name[0].given +',
    composition: 'Patient.name[0].given.first()',
  },
  'precedence.index-unary': {
    family: 'precedence',
    source: {
      expression: '-Patient.name.given[0].length()',
      corpusGap: 'focused adjacent index/unary precedence case',
    },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '-Patient.name.given[0].length() +',
    composition: '(-Patient.name.given[0].length()).toString()',
  },
  'precedence.unary-multiplicative': {
    family: 'precedence',
    source: { expression: '-1 * 2', corpusGap: 'focused adjacent unary/multiplicative precedence case' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '-1 *',
    composition: '(-1 * 2).toString()',
  },
  'precedence.multiplicative-additive': {
    family: 'precedence',
    source: { expression: '1 + 2 * 3', corpusGap: 'focused adjacent multiplicative/additive precedence case' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer'], single: true },
    degradation: '1 + 2 *',
    composition: '(1 + 2 * 3).toString()',
  },
  'precedence.additive-type': {
    family: 'precedence',
    source: { expression: '1 + 2 is Integer', corpusGap: 'focused adjacent additive/type precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 + 2 is Nope',
    composition: '(1 + 2 is Integer).toString()',
  },
  'precedence.type-union': {
    family: 'precedence',
    source: { expression: '1 | 2 is Integer', corpusGap: 'focused adjacent type/union precedence case' },
    expectedType: '(number | boolean)[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Integer', 'System.Boolean'], single: false },
    degradation: '1 | 2 is Nope',
    composition: '(1 | 2 is Integer).toString()',
  },
  'precedence.union-comparison': {
    family: 'precedence',
    source: { expression: '1 < 2 | 2', corpusGap: 'focused adjacent union/comparison precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 < 2 |',
    composition: '(1 < 2 | 2).toString()',
  },
  'precedence.comparison-equality': {
    family: 'precedence',
    source: { expression: 'true = 1 < 2', corpusGap: 'focused adjacent comparison/equality precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true = 1 <',
    composition: '(true = 1 < 2).toString()',
  },
  'precedence.equality-membership': {
    family: 'precedence',
    source: { expression: '1 in 1 = 1', corpusGap: 'focused adjacent equality/membership precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 in 1 =',
    composition: '(1 in 1 = 1).toString()',
  },
  'precedence.membership-and': {
    family: 'precedence',
    source: { expression: '1 in (1 | 2) and true', corpusGap: 'focused adjacent membership/and precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: '1 in (1 | 2) and',
    composition: '(1 in (1 | 2) and true).toString()',
  },
  'precedence.and-or': {
    family: 'precedence',
    source: { expression: 'true or false and false', corpusGap: 'focused adjacent and/or precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true or false and',
    composition: '(true or false and false).toString()',
  },
  'precedence.or-implies': {
    family: 'precedence',
    source: { expression: 'true implies false or true', corpusGap: 'focused adjacent or/implies precedence case' },
    expectedType: 'boolean[]',
    compositionType: 'string[]',
    runtime: true,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: 'true implies false or',
    composition: '(true implies false or true).toString()',
  },
  'scope.this': {
    family: 'function-lambda',
    source: { expression: 'Patient.name.select($this.family)', corpusGap: 'focused lambda-frame type assertion' },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: 'Patient.name.select($this.nope)',
    composition: 'Patient.name.select($this.family).upper()',
  },
  'scope.index': {
    family: 'function-lambda',
    source: { expression: 'Patient.name.select($index)', corpusGap: 'focused lambda index assertion' },
    expectedType: 'number[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['System.Integer'], single: false },
    degradation: 'Patient.name.select($index.nope)',
    composition: 'Patient.name.select($index).first().toString()',
  },
  'scope.total': {
    family: 'function-lambda',
    source: {
      expression: "Patient.name.aggregate($total.toString(), '')",
      corpusGap: 'focused aggregate accumulator-frame assertion',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['System.String'], single: true },
    degradation: 'Patient.name.aggregate($total.nope, {})',
    composition: "Patient.name.aggregate($total.toString(), '').upper()",
  },
  'scope.nested-frame-restore': {
    family: 'function-lambda',
    source: {
      expression: 'Patient.name.select(given.select($this.substring(1)) | family)',
      corpusGap: 'focused nested lambda-frame restoration assertion',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['System.String', 'FHIR.string'], single: false },
    degradation: 'Patient.name.select(given.select($this.nope) | family)',
    composition: 'Patient.name.select(given.select($this.substring(1)) | family).first()',
  },
  'scope.define-variable-input': {
    family: 'variable',
    source: {
      expression: "Patient.name.first().defineVariable('n').select(%n.family)",
      corpusGap: 'focused inferred defineVariable input binding',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: true },
    degradation: "Patient.name.first().defineVariable('n').select(%missing)",
    composition: "Patient.name.first().defineVariable('n').select(%n.family).upper()",
  },
  'scope.define-variable-value': {
    family: 'variable',
    source: {
      expression: "Patient.defineVariable('n', name.first()).select(%n.family)",
      corpusGap: 'focused inferred defineVariable expression binding',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: true },
    degradation: "Patient.defineVariable('n', name.first()).select(%missing)",
    composition: "Patient.defineVariable('n', name.first()).select(%n.family).upper()",
  },
  'scope.nested-binding-restore': {
    family: 'variable',
    source: {
      expression: "Patient.name.first().defineVariable('n').select(given.select(%n.family))",
      corpusGap: 'focused binding restoration through a nested lambda frame',
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: "Patient.name.first().defineVariable('n').select(given.select(%missing))",
    composition: "Patient.name.first().defineVariable('n').select(given.select(%n.family)).first()",
  },
  'scope.multiple-definition-fallback': {
    family: 'variable',
    source: { corpusId: 'official:r5:defineVariable:dvConceptMapExample' },
    expectedType: 'boolean[]',
    compositionType: 'number[]',
    runtime: false,
    analyzer: { types: ['System.Boolean'], single: true },
    degradation: "defineVariable('a').select(%missing)",
    composition: "defineVariable('a').defineVariable('b').count()",
  },
  'scope.operator-fork': {
    family: 'variable',
    source: {
      expression: "Patient.defineVariable('left').active | %left",
      corpusGap: 'focused branch-local operator scope assertion',
    },
    expectedType: 'unknown[]',
    compositionType: 'number[]',
    runtime: false,
    analyzer: { types: undefined, single: false },
    degradation: "Patient.defineVariable('left').active | %missing",
    composition: "(Patient.defineVariable('left').active | %left).count()",
  },
  'scope.argument-fork': {
    family: 'variable',
    source: {
      expression: "Patient.select(defineVariable('inner').active).select(%inner)",
      corpusGap: 'focused branch-local argument scope assertion',
    },
    expectedType: 'unknown[]',
    compositionType: 'number[]',
    runtime: false,
    analyzer: { types: undefined, single: undefined },
    degradation: "Patient.select(defineVariable('inner').active).select(%missing)",
    composition: "Patient.select(defineVariable('inner').active).select(%inner).count()",
  },
  'variable.context-root': {
    family: 'variable',
    source: { expression: '%context.name.given', corpusGap: 'typed built-in root variable assertion' },
    input: 'Patient',
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '%context.nope',
    composition: '%context.name.given.first()',
  },
  'variable.resource-root': {
    family: 'variable',
    source: { expression: '%resource.name.family', corpusGap: 'typed built-in resource variable assertion' },
    input: 'Patient',
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '%resource.nope',
    composition: '%resource.name.family.first()',
  },
  'variable.root-resource': {
    family: 'variable',
    source: { expression: '%rootResource.name.family', corpusGap: 'typed built-in rootResource assertion' },
    input: 'Patient',
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '%rootResource.nope',
    composition: '%rootResource.name.family.first()',
  },
  'variable.builtin-constant': {
    family: 'variable',
    source: { expression: '%loinc.upper()', corpusGap: 'typed built-in terminology constant assertion' },
    expectedType: 'string[]',
    compositionType: 'number[]',
    runtime: false,
    analyzer: { types: ['System.String'], single: true },
    degradation: '%loinc.nope',
    composition: '%loinc.upper().length()',
  },
  'reference.generated-targets': {
    family: 'reference',
    source: {
      expression: 'Patient.generalPractitioner.resolve()',
      corpusGap: 'focused generated Reference target union assertion',
    },
    expectedType: "R4TypeOf['Organization' | 'Practitioner' | 'PractitionerRole'][]",
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.Organization', 'FHIR.Practitioner', 'FHIR.PractitionerRole'], single: false },
    degradation: 'Bundle.entry.resource.resolve()',
    composition: 'Patient.generalPractitioner.resolve().ofType(Organization).name',
  },
  'reference.state-preservation': {
    family: 'reference',
    source: {
      expression: 'Patient.generalPractitioner.where($this.exists())[0].resolve()',
      corpusGap: 'focused Reference target propagation through filter and index',
    },
    expectedType: "R4TypeOf['Organization' | 'Practitioner' | 'PractitionerRole'][]",
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.Organization', 'FHIR.Practitioner', 'FHIR.PractitionerRole'], single: true },
    degradation: 'Bundle.entry.resource.where($this.exists())[0].resolve()',
    composition: 'Patient.generalPractitioner.where($this.exists())[0].resolve().ofType(Organization).name',
  },
  'host-context.environment': {
    family: 'host-context',
    source: { expression: '%report.status', corpusGap: 'host declaration route assertion' },
    typeContext: { env: { report: { type: 'DiagnosticReport' } } },
    context: { variables: { report: { types: ['DiagnosticReport'], single: true } } },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.code'], single: true },
    degradation: '%report.nope',
    composition: '%report.status.first()',
  },
  'host-context.variable': {
    family: 'host-context',
    source: { expression: '%subject.name.given', corpusGap: 'pre-resolved var declaration route assertion' },
    typeContext: { vars: { subject: { type: 'Patient' } } },
    context: { variables: { subject: { types: ['Patient'], single: true } } },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '%subject.nope',
    composition: '%subject.name.given.first()',
  },
  'host-context.function-signature': {
    family: 'host-context',
    source: { expression: 'Patient.statusText()', corpusGap: 'custom signature route assertion' },
    typeContext: {
      functions: {
        statusText: { expression: "'fallback'", signature: { result: { types: ['string'], single: true } } },
      },
    },
    context: {
      functions: {
        statusText: { expression: "'fallback'", signature: { result: { types: ['string'], single: true } } },
      },
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: true },
    degradation: 'Patient.missingFunction()',
    composition: 'Patient.statusText().upper()',
  },
  'host-context.function-body': {
    family: 'host-context',
    source: { expression: 'Condition.code.displayText()', corpusGap: 'literal function-body route assertion' },
    typeContext: { functions: { displayText: { expression: '(text | coding.display).first()' } } },
    context: { functions: { displayText: { expression: '(text | coding.display).first()' } } },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: true },
    degradation: 'Condition.code.displayText().nope',
    composition: 'Condition.code.displayText().upper()',
  },
  'host-context.function-local-overlay': {
    family: 'host-context',
    source: { expression: 'Condition.code.labelled()', corpusGap: 'function-local envTypes route assertion' },
    typeContext: {
      functions: {
        labelled: { expression: '%prefix & text', envTypes: { prefix: { type: 'string' } } },
      },
    },
    context: {
      functions: {
        labelled: { expression: '%prefix & text', envTypes: { prefix: { type: 'string' } } },
      },
    },
    expectedType: 'string[]',
    compositionType: 'number[]',
    runtime: false,
    analyzer: { types: ['System.String'], single: true },
    degradation: 'Condition.code.labelled().nope',
    composition: 'Condition.code.labelled().length()',
  },
  'host-context.reference-targets': {
    family: 'host-context',
    source: { expression: '%subject.resolve().name.given', corpusGap: 'declared Reference target route assertion' },
    typeContext: { env: { subject: { type: 'Reference', targets: 'Practitioner' } } },
    context: {
      variables: { subject: { types: ['Reference'], single: true, targets: ['Practitioner'] } },
    },
    expectedType: 'string[]',
    compositionType: 'string[]',
    runtime: false,
    analyzer: { types: ['FHIR.string'], single: false },
    degradation: '%subject.resolve().nope',
    composition: '%subject.resolve().name.given.first()',
  },
  ...BUILTIN_FUNCTION_CAPABILITIES,
} as const satisfies Record<string, CapabilityEntry>

export type InferenceCapabilityId = keyof typeof INFERENCE_CAPABILITIES
