// Generated by scripts/generate-type-metadata.ts. Do not edit by hand.

export interface CompactFunctionRules {
  abs: readonly ['unknown']
  aggregate: readonly ['union', 0 | 1]
  all: readonly ['fixed', 'System.Boolean']
  allFalse: readonly ['fixed', 'System.Boolean']
  allTrue: readonly ['fixed', 'System.Boolean']
  anyFalse: readonly ['fixed', 'System.Boolean']
  anyTrue: readonly ['fixed', 'System.Boolean']
  as: readonly ['unknown']
  avg: readonly ['fixed', 'System.Decimal']
  ceiling: readonly ['fixed', 'System.Integer']
  children: readonly ['unknown']
  coalesce: readonly ['arguments-union']
  combine: readonly ['union', 'input' | 0]
  comparable: readonly ['fixed', 'System.Boolean']
  conformsTo: readonly ['fixed', 'System.Boolean']
  contains: readonly ['fixed', 'System.Boolean']
  convertsToBoolean: readonly ['fixed', 'System.Boolean']
  convertsToDate: readonly ['fixed', 'System.Boolean']
  convertsToDateTime: readonly ['fixed', 'System.Boolean']
  convertsToDecimal: readonly ['fixed', 'System.Boolean']
  convertsToInteger: readonly ['fixed', 'System.Boolean']
  convertsToLong: readonly ['fixed', 'System.Boolean']
  convertsToQuantity: readonly ['fixed', 'System.Boolean']
  convertsToString: readonly ['fixed', 'System.Boolean']
  convertsToTime: readonly ['fixed', 'System.Boolean']
  count: readonly ['fixed', 'System.Integer']
  dateOf: readonly ['fixed', 'System.Date']
  dayOf: readonly ['fixed', 'System.Integer']
  decode: readonly ['fixed', 'System.String']
  defineVariable: readonly ['input']
  descendants: readonly ['unknown']
  distinct: readonly ['input']
  empty: readonly ['fixed', 'System.Boolean']
  encode: readonly ['fixed', 'System.String']
  endsWith: readonly ['fixed', 'System.Boolean']
  escape: readonly ['fixed', 'System.String']
  exclude: readonly ['input']
  exists: readonly ['fixed', 'System.Boolean']
  exp: readonly ['fixed', 'System.Decimal']
  extension: readonly ['unknown']
  first: readonly ['input']
  floor: readonly ['fixed', 'System.Integer']
  getValue: readonly ['unknown']
  hasValue: readonly ['fixed', 'System.Boolean']
  highBoundary: readonly ['unknown']
  hourOf: readonly ['fixed', 'System.Integer']
  htmlChecks: readonly ['fixed', 'System.Boolean']
  iif: readonly ['union', 1 | 2]
  indexOf: readonly ['fixed', 'System.Integer']
  intersect: readonly ['input']
  is: readonly ['fixed', 'System.Boolean']
  isDistinct: readonly ['fixed', 'System.Boolean']
  join: readonly ['fixed', 'System.String']
  last: readonly ['input']
  lastIndexOf: readonly ['fixed', 'System.Integer']
  length: readonly ['fixed', 'System.Integer']
  ln: readonly ['fixed', 'System.Decimal']
  log: readonly ['fixed', 'System.Decimal']
  lowBoundary: readonly ['unknown']
  lower: readonly ['fixed', 'System.String']
  matches: readonly ['fixed', 'System.Boolean']
  matchesFull: readonly ['fixed', 'System.Boolean']
  max: readonly ['unknown']
  millisecondOf: readonly ['fixed', 'System.Integer']
  min: readonly ['unknown']
  minuteOf: readonly ['fixed', 'System.Integer']
  monthOf: readonly ['fixed', 'System.Integer']
  not: readonly ['fixed', 'System.Boolean']
  now: readonly ['fixed', 'System.DateTime']
  ofType: readonly ['unknown']
  power: readonly ['unknown']
  precision: readonly ['fixed', 'System.Integer']
  repeat: readonly ['unknown']
  replace: readonly ['fixed', 'System.String']
  replaceMatches: readonly ['fixed', 'System.String']
  resolve: readonly ['reference-targets']
  round: readonly ['fixed', 'System.Decimal']
  secondOf: readonly ['fixed', 'System.Integer']
  select: readonly ['argument', 0]
  single: readonly ['input']
  skip: readonly ['input']
  sort: readonly ['input']
  split: readonly ['fixed', 'System.String']
  sqrt: readonly ['fixed', 'System.Decimal']
  startsWith: readonly ['fixed', 'System.Boolean']
  subsetOf: readonly ['fixed', 'System.Boolean']
  substring: readonly ['fixed', 'System.String']
  sum: readonly ['unknown']
  supersetOf: readonly ['fixed', 'System.Boolean']
  tail: readonly ['input']
  take: readonly ['input']
  timeOf: readonly ['fixed', 'System.Time']
  timeOfDay: readonly ['fixed', 'System.Time']
  timezoneOffsetOf: readonly ['fixed', 'System.Decimal']
  toBoolean: readonly ['fixed', 'System.Boolean']
  toChars: readonly ['fixed', 'System.String']
  toDate: readonly ['fixed', 'System.Date']
  toDateTime: readonly ['fixed', 'System.DateTime']
  today: readonly ['fixed', 'System.Date']
  toDecimal: readonly ['fixed', 'System.Decimal']
  toInteger: readonly ['fixed', 'System.Integer']
  toLong: readonly ['fixed', 'System.Long']
  toQuantity: readonly ['fixed', 'System.Quantity']
  toString: readonly ['fixed', 'System.String']
  toTime: readonly ['fixed', 'System.Time']
  trace: readonly ['input']
  trim: readonly ['fixed', 'System.String']
  truncate: readonly ['fixed', 'System.Integer']
  type: readonly ['unknown']
  unescape: readonly ['fixed', 'System.String']
  union: readonly ['union', 'input' | 0]
  upper: readonly ['fixed', 'System.String']
  where: readonly ['input']
  yearOf: readonly ['fixed', 'System.Integer']
}

export interface CompactFunctionArguments {
  abs: readonly []
  aggregate: readonly ['expression', 'any']
  all: readonly ['expression']
  allFalse: readonly []
  allTrue: readonly []
  anyFalse: readonly []
  anyTrue: readonly []
  as: readonly ['type-name']
  avg: readonly []
  ceiling: readonly []
  children: readonly []
  coalesce: readonly ['expression']
  combine: readonly ['any']
  comparable: readonly ['Quantity']
  conformsTo: readonly ['String']
  contains: readonly ['String']
  convertsToBoolean: readonly []
  convertsToDate: readonly []
  convertsToDateTime: readonly []
  convertsToDecimal: readonly []
  convertsToInteger: readonly []
  convertsToLong: readonly []
  convertsToQuantity: readonly ['String']
  convertsToString: readonly []
  convertsToTime: readonly []
  count: readonly []
  dateOf: readonly []
  dayOf: readonly []
  decode: readonly ['String']
  defineVariable: readonly ['String', 'expression']
  descendants: readonly []
  distinct: readonly []
  empty: readonly []
  encode: readonly ['String']
  endsWith: readonly ['String']
  escape: readonly ['String']
  exclude: readonly ['any']
  exists: readonly ['expression']
  exp: readonly []
  extension: readonly ['String']
  first: readonly []
  floor: readonly []
  getValue: readonly []
  hasValue: readonly []
  highBoundary: readonly ['Numeric']
  hourOf: readonly []
  htmlChecks: readonly []
  iif: readonly ['condition', 'expression', 'expression']
  indexOf: readonly ['String']
  intersect: readonly ['any']
  is: readonly ['type-name']
  isDistinct: readonly []
  join: readonly ['String']
  last: readonly []
  lastIndexOf: readonly ['String']
  length: readonly []
  ln: readonly []
  log: readonly ['Numeric']
  lowBoundary: readonly ['Numeric']
  lower: readonly []
  matches: readonly ['String']
  matchesFull: readonly ['String']
  max: readonly []
  millisecondOf: readonly []
  min: readonly []
  minuteOf: readonly []
  monthOf: readonly []
  not: readonly []
  now: readonly []
  ofType: readonly ['type-name']
  power: readonly ['Numeric']
  precision: readonly []
  repeat: readonly ['expression']
  replace: readonly ['String', 'String']
  replaceMatches: readonly ['String', 'String']
  resolve: readonly []
  round: readonly ['Numeric']
  secondOf: readonly []
  select: readonly ['expression']
  single: readonly []
  skip: readonly ['Numeric']
  sort: readonly ['sort-key']
  split: readonly ['String']
  sqrt: readonly []
  startsWith: readonly ['String']
  subsetOf: readonly ['any']
  substring: readonly ['Numeric', 'Numeric']
  sum: readonly []
  supersetOf: readonly ['any']
  tail: readonly []
  take: readonly ['Numeric']
  timeOf: readonly []
  timeOfDay: readonly []
  timezoneOffsetOf: readonly []
  toBoolean: readonly []
  toChars: readonly []
  toDate: readonly []
  toDateTime: readonly []
  today: readonly []
  toDecimal: readonly []
  toInteger: readonly []
  toLong: readonly []
  toQuantity: readonly ['String']
  toString: readonly []
  toTime: readonly []
  trace: readonly ['String', 'expression']
  trim: readonly []
  truncate: readonly []
  type: readonly []
  unescape: readonly ['String']
  union: readonly ['any']
  upper: readonly []
  where: readonly ['expression']
  yearOf: readonly []
}

export type CompactLambdaArgument0Name =
  'exists' | 'all' | 'where' | 'select' | 'repeat' | 'iif' | 'aggregate' | 'sort' | 'coalesce'
export type CompactLambdaArgument1Name =
  'exists' | 'all' | 'where' | 'select' | 'repeat' | 'iif' | 'trace' | 'sort' | 'defineVariable' | 'coalesce'
export type CompactLambdaArgument2Name =
  'exists' | 'all' | 'where' | 'select' | 'repeat' | 'iif' | 'trace' | 'sort' | 'defineVariable' | 'coalesce'

export type CompactFastFunctionName =
  | 'empty'
  | 'exists'
  | 'all'
  | 'allTrue'
  | 'anyTrue'
  | 'allFalse'
  | 'anyFalse'
  | 'count'
  | 'distinct'
  | 'isDistinct'
  | 'subsetOf'
  | 'supersetOf'
  | 'where'
  | 'is'
  | 'single'
  | 'first'
  | 'last'
  | 'tail'
  | 'skip'
  | 'take'
  | 'intersect'
  | 'exclude'
  | 'not'
  | 'trace'
  | 'hasValue'
  | 'htmlChecks'
  | 'comparable'
  | 'conformsTo'
  | 'length'
  | 'indexOf'
  | 'lastIndexOf'
  | 'substring'
  | 'startsWith'
  | 'endsWith'
  | 'contains'
  | 'upper'
  | 'lower'
  | 'replace'
  | 'matches'
  | 'matchesFull'
  | 'replaceMatches'
  | 'toChars'
  | 'trim'
  | 'split'
  | 'join'
  | 'encode'
  | 'decode'
  | 'escape'
  | 'unescape'
  | 'ceiling'
  | 'floor'
  | 'truncate'
  | 'round'
  | 'exp'
  | 'ln'
  | 'sqrt'
  | 'log'
  | 'avg'
  | 'sort'
  | 'toBoolean'
  | 'toInteger'
  | 'toLong'
  | 'toDecimal'
  | 'toString'
  | 'toDate'
  | 'toDateTime'
  | 'toTime'
  | 'toQuantity'
  | 'convertsToBoolean'
  | 'convertsToInteger'
  | 'convertsToLong'
  | 'convertsToDecimal'
  | 'convertsToString'
  | 'convertsToDate'
  | 'convertsToDateTime'
  | 'convertsToTime'
  | 'convertsToQuantity'
  | 'now'
  | 'today'
  | 'timeOfDay'
  | 'yearOf'
  | 'monthOf'
  | 'dayOf'
  | 'hourOf'
  | 'minuteOf'
  | 'secondOf'
  | 'millisecondOf'
  | 'timezoneOffsetOf'
  | 'dateOf'
  | 'timeOf'
  | 'precision'

export interface CompactOperatorRules {
  '*': readonly ['arithmetic']
  '/': readonly ['arithmetic']
  div: readonly ['arithmetic']
  mod: readonly ['arithmetic']
  '+': readonly ['arithmetic']
  '-': readonly ['arithmetic']
  '&': readonly ['fixed', 'System.String']
  '|': readonly ['union']
  '<': readonly ['fixed', 'System.Boolean']
  '>': readonly ['fixed', 'System.Boolean']
  '<=': readonly ['fixed', 'System.Boolean']
  '>=': readonly ['fixed', 'System.Boolean']
  '=': readonly ['fixed', 'System.Boolean']
  '~': readonly ['fixed', 'System.Boolean']
  '!=': readonly ['fixed', 'System.Boolean']
  '!~': readonly ['fixed', 'System.Boolean']
  in: readonly ['fixed', 'System.Boolean']
  contains: readonly ['fixed', 'System.Boolean']
  and: readonly ['fixed', 'System.Boolean']
  or: readonly ['fixed', 'System.Boolean']
  xor: readonly ['fixed', 'System.Boolean']
  implies: readonly ['fixed', 'System.Boolean']
}

export interface CompactTypeOperatorRules {
  is: readonly ['fixed', 'System.Boolean']
  as: readonly ['narrow']
}

export interface CompactPrefixParselets {
  identifier: readonly ['identifier', 'prefix', 0, 'none', 'none', 'identifier']
  literal: readonly ['literal', 'prefix', 0, 'none', 'none', 'literal']
  variable: readonly ['variable', 'prefix', 0, 'none', 'none', 'identifier']
  '+': readonly ['operator', 'prefix', 11, 'right', 'expression', 'unary']
  '-': readonly ['operator', 'prefix', 11, 'right', 'expression', 'unary']
  '(': readonly ['punct', 'prefix', 0, 'none', 'group', 'group']
  '{': readonly ['punct', 'prefix', 0, 'none', 'none', 'empty']
  '%': readonly ['punct', 'prefix', 0, 'none', 'external-name', 'external']
}

export interface CompactInfixParselets {
  implies: readonly ['keyword', 'infix', 1, 'left', 'expression', 'binary']
  or: readonly ['keyword', 'infix', 2, 'left', 'expression', 'binary']
  xor: readonly ['keyword', 'infix', 2, 'left', 'expression', 'binary']
  and: readonly ['keyword', 'infix', 3, 'left', 'expression', 'binary']
  in: readonly ['keyword', 'infix', 4, 'left', 'expression', 'binary']
  contains: readonly ['keyword', 'infix', 4, 'left', 'expression', 'binary']
  '=': readonly ['operator', 'infix', 5, 'left', 'expression', 'binary']
  '~': readonly ['operator', 'infix', 5, 'left', 'expression', 'binary']
  '!=': readonly ['operator', 'infix', 5, 'left', 'expression', 'binary']
  '!~': readonly ['operator', 'infix', 5, 'left', 'expression', 'binary']
  '<': readonly ['operator', 'infix', 6, 'left', 'expression', 'binary']
  '>': readonly ['operator', 'infix', 6, 'left', 'expression', 'binary']
  '<=': readonly ['operator', 'infix', 6, 'left', 'expression', 'binary']
  '>=': readonly ['operator', 'infix', 6, 'left', 'expression', 'binary']
  '|': readonly ['operator', 'infix', 7, 'left', 'expression', 'binary']
  is: readonly ['keyword', 'infix', 8, 'left', 'type-name', 'type']
  as: readonly ['keyword', 'infix', 8, 'left', 'type-name', 'type']
  '+': readonly ['operator', 'infix', 9, 'left', 'expression', 'binary']
  '-': readonly ['operator', 'infix', 9, 'left', 'expression', 'binary']
  '&': readonly ['operator', 'infix', 9, 'left', 'expression', 'binary']
  '*': readonly ['operator', 'infix', 10, 'left', 'expression', 'binary']
  '/': readonly ['operator', 'infix', 10, 'left', 'expression', 'binary']
  div: readonly ['keyword', 'infix', 10, 'left', 'expression', 'binary']
  mod: readonly ['keyword', 'infix', 10, 'left', 'expression', 'binary']
  '[': readonly ['punct', 'postfix', 12, 'left', 'index', 'indexer']
  '.': readonly ['punct', 'infix', 13, 'left', 'path', 'dot']
  '(': readonly ['punct', 'postfix', 14, 'left', 'arguments', 'call']
}

export type CompactCalendarUnit =
  | 'day'
  | 'days'
  | 'hour'
  | 'hours'
  | 'millisecond'
  | 'milliseconds'
  | 'minute'
  | 'minutes'
  | 'month'
  | 'months'
  | 'second'
  | 'seconds'
  | 'week'
  | 'weeks'
  | 'year'
  | 'years'
