// Importing this module registers the function library into the registry table.
// The evaluator imports it for its side effects; later phases append more modules.
import './aggregate.ts'
import './boundary.ts'
import './combining.ts'
import './conversion.ts'
import './date-components.ts'
import './control.ts'
import './existence.ts'
import './fhir.ts'
import './filtering.ts'
import './math.ts'
import './reflection.ts'
import './sort.ts'
import './string.ts'
import './subsetting.ts'
import './tree.ts'
import './variables.ts'
import './utility.ts'
