import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { FUNCTION_SIGNATURES } from '../src/analyzer/signatures.ts'
import { tokenize } from '../src/lexer/lexer.ts'
import type { AstNode } from '../src/parser/ast.ts'
import { parse } from '../src/parser/parser.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { type InventoryCase, loadInferenceInventory } from './inference-corpus.ts'

function visit(node: AstNode, operators: Set<string>, functions: Set<string>, literals: Set<string>): void {
  switch (node.kind) {
    case 'null':
    case 'boolean':
    case 'string':
    case 'number':
    case 'date':
    case 'dateTime':
    case 'time':
    case 'quantity':
      literals.add(
        node.kind === 'number' && node.isLong
          ? 'long'
          : node.kind === 'number' && node.isDecimal
            ? 'decimal'
            : node.kind
      )
      return
    case 'identifier':
    case 'special':
    case 'external':
      return
    case 'dot':
      visit(node.left, operators, functions, literals)
      visit(node.right, operators, functions, literals)
      return
    case 'indexer':
      visit(node.target, operators, functions, literals)
      visit(node.index, operators, functions, literals)
      return
    case 'call':
      functions.add(node.name)
      for (const argument of node.args) visit(argument, operators, functions, literals)
      return
    case 'unary':
      operators.add(`unary${node.operator}`)
      visit(node.operand, operators, functions, literals)
      return
    case 'binary':
      operators.add(node.operator)
      visit(node.left, operators, functions, literals)
      visit(node.right, operators, functions, literals)
      return
    case 'typeOp':
      operators.add(node.operator)
      visit(node.operand, operators, functions, literals)
      return
  }
}

const all = loadInferenceInventory()
const byExpression = new Map<string, InventoryCase>()
for (const item of all) byExpression.set(item.expression, item)

const accepted: { item: InventoryCase; tokens: number; sourceSteps: number }[] = []
const rejected: { id: string; expression: string; error: string }[] = []
const operators = new Set<string>()
const calledFunctions = new Set<string>()
const literals = new Set<string>()
for (const item of byExpression.values()) {
  try {
    const tokens = tokenize(item.expression).length - 1
    const ast = parse(item.expression)
    accepted.push({ item, tokens, sourceSteps: item.expression.length })
    visit(ast, operators, calledFunctions, literals)
  } catch (error) {
    rejected.push({
      id: item.id,
      expression: item.expression,
      error: error instanceof Error ? error.message : String(error),
    })
  }
}

const withinBudget = accepted.filter(item => item.tokens <= 64 && item.sourceSteps <= 256)
const overBudget = accepted.filter(item => item.tokens > 64 || item.sourceSteps > 256)
const signedFunctions = Object.keys(FUNCTION_SIGNATURES).sort()
const report = {
  totalCases: all.length,
  distinctExpressions: byExpression.size,
  accepted: accepted.length,
  rejected: rejected.length,
  withinBudget: withinBudget.length,
  overBudget: overBudget.map(item => ({
    id: item.item.id,
    expression: item.item.expression,
    tokens: item.tokens,
    sourceSteps: item.sourceSteps,
  })),
  longestWithinBudget: Math.max(...withinBudget.map(item => item.sourceSteps)),
  maxTokensWithinBudget: Math.max(...withinBudget.map(item => item.tokens)),
  operators: [...operators].sort(),
  literals: [...literals].sort(),
  signedFunctions: signedFunctions.length,
  coveredSignedFunctions: signedFunctions.filter(name => calledFunctions.has(name)),
  missingSignedFunctions: signedFunctions.filter(name => !calledFunctions.has(name)),
  rejectedExpressions: rejected,
} as const

const source = await formatGeneratedTypeScript(`// Generated by scripts/audit-inference-corpus.ts. Do not edit by hand.

export const INFERENCE_CORPUS_AUDIT = ${JSON.stringify(report, null, 2)} as const
`)
const output = new URL('../src/typed/generated/corpus-audit.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== source) {
    console.error(`${fileURLToPath(output)} is stale; run pnpm generate:inference-corpus`)
    process.exit(1)
  }
} else {
  writeFileSync(output, source)
  console.log(JSON.stringify(report, null, 2))
}
