import { FUNCTION_SIGNATURES } from '../src/analyzer/signatures.ts'
import { tokenize } from '../src/lexer/lexer.ts'
import { parse } from '../src/parser/parser.ts'
import { INFERENCE_SOURCE_STEP_LIMIT, INFERENCE_TOKEN_LIMIT } from '../src/typed/inference-limits.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { writeOrCheckGenerated } from './generated-file.ts'
import { type InventoryCase, loadInferenceInventory } from './inference-corpus.ts'
import { walkAst } from './walk-ast.ts'

const all = loadInferenceInventory()
const byExpression = new Map<string, InventoryCase>()
for (const item of all) byExpression.set(item.expression, item)

const accepted: { item: InventoryCase; tokens: number; sourceSteps: number }[] = []
const rejected: { id: string; expression: string; error: string }[] = []
const operators = new Set<string>()
const calledFunctions = new Set<string>()
const literals = new Set<string>()
for (const item of byExpression.values()) {
  try {
    const tokens = tokenize(item.expression).length - 1
    const ast = parse(item.expression)
    accepted.push({ item, tokens, sourceSteps: item.expression.length })
    walkAst(ast, node => {
      switch (node.kind) {
        case 'null':
        case 'boolean':
        case 'string':
        case 'number':
        case 'date':
        case 'dateTime':
        case 'time':
        case 'quantity':
          literals.add(
            node.kind === 'number' && node.isLong
              ? 'long'
              : node.kind === 'number' && node.isDecimal
                ? 'decimal'
                : node.kind
          )
          break
        case 'call':
          calledFunctions.add(node.name)
          break
        case 'unary':
          operators.add(`unary${node.operator}`)
          break
        case 'binary':
        case 'typeOp':
          operators.add(node.operator)
          break
      }
    })
  } catch (error) {
    rejected.push({
      id: item.id,
      expression: item.expression,
      error: error instanceof Error ? error.message : String(error),
    })
  }
}

const withinBudget = accepted.filter(
  item => item.tokens <= INFERENCE_TOKEN_LIMIT && item.sourceSteps <= INFERENCE_SOURCE_STEP_LIMIT
)
const overBudget = accepted.filter(
  item => item.tokens > INFERENCE_TOKEN_LIMIT || item.sourceSteps > INFERENCE_SOURCE_STEP_LIMIT
)
const longestWithinBudgetCase = [...withinBudget].sort(
  (left, right) => right.sourceSteps - left.sourceSteps || left.item.id.localeCompare(right.item.id)
)[0]
const signedFunctions = Object.keys(FUNCTION_SIGNATURES).sort()
const report = {
  totalCases: all.length,
  distinctExpressions: byExpression.size,
  accepted: accepted.length,
  rejected: rejected.length,
  withinBudget: withinBudget.length,
  overBudget: overBudget.map(item => ({
    id: item.item.id,
    expression: item.item.expression,
    tokens: item.tokens,
    sourceSteps: item.sourceSteps,
  })),
  longestWithinBudget: Math.max(...withinBudget.map(item => item.sourceSteps)),
  longestWithinBudgetCase:
    longestWithinBudgetCase === undefined
      ? undefined
      : {
          id: longestWithinBudgetCase.item.id,
          expression: longestWithinBudgetCase.item.expression,
          ...(longestWithinBudgetCase.item.inputType !== undefined && {
            inputType: longestWithinBudgetCase.item.inputType,
          }),
          tokens: longestWithinBudgetCase.tokens,
          sourceSteps: longestWithinBudgetCase.sourceSteps,
        },
  maxTokensWithinBudget: Math.max(...withinBudget.map(item => item.tokens)),
  operators: [...operators].sort(),
  literals: [...literals].sort(),
  signedFunctions: signedFunctions.length,
  coveredSignedFunctions: signedFunctions.filter(name => calledFunctions.has(name)),
  missingSignedFunctions: signedFunctions.filter(name => !calledFunctions.has(name)),
  rejectedExpressions: rejected,
} as const

const source = await formatGeneratedTypeScript(`// Generated by scripts/audit-inference-corpus.ts. Do not edit by hand.

export const INFERENCE_CORPUS_AUDIT = ${JSON.stringify(report, null, 2)} as const
`)
const output = new URL('../src/typed/generated/corpus-audit.ts', import.meta.url)
writeOrCheckGenerated(output, source, {
  check: process.argv.includes('--check'),
  regenerate: 'pnpm generate:inference-corpus',
})
if (!process.argv.includes('--check')) console.log(JSON.stringify(report, null, 2))
