import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { INFERENCE_CAPABILITIES } from '../src/typed/capability-registry.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { loadInferenceInventory } from './inference-corpus.ts'

const corpus = new Map(loadInferenceInventory().map(item => [item.id, item]))
const resolved = Object.fromEntries(
  Object.entries(INFERENCE_CAPABILITIES).map(([id, capability]) => {
    const corpusCase = 'corpusId' in capability.source ? corpus.get(capability.source.corpusId) : undefined
    const expression =
      corpusCase?.expression ?? ('expression' in capability.source ? capability.source.expression : undefined)
    if (expression === undefined) {
      throw new Error(
        `${id}: corpus id ${'corpusId' in capability.source ? capability.source.corpusId : ''} does not resolve`
      )
    }
    return [
      id,
      {
        ...capability,
        expression,
        ...(corpusCase !== undefined && {
          reference: corpusCase.reference,
          ...(corpusCase.inputType !== undefined && { inputType: corpusCase.inputType }),
        }),
      },
    ]
  })
)

const source =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-inference-capabilities.ts. Do not edit by hand.

export const RESOLVED_INFERENCE_CAPABILITIES = ${stringifyWithUndefined(resolved)} as const
`)
const output = new URL('../src/typed/generated/capabilities.ts', import.meta.url)
const assertions =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-inference-capabilities.ts. Do not edit by hand.

import type { HumanName, R4TypeOf, SystemQuantity } from '../../r4/generated/type-maps.ts'
import type { FhirpathResultIn } from '../infer.ts'

type Equal<Left, Right> = (<Type>() => Type extends Left ? 1 : 2) extends <Type>() => Type extends Right ? 1 : 2
  ? true
  : false
type Assert<Condition extends true> = Condition

${Object.entries(resolved)
  .flatMap(([id, capability]) => {
    const name = id
      .split(/[^A-Za-z0-9]+/)
      .filter(Boolean)
      .map(part => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
      .join('')
    const input = 'input' in capability ? capability.input : 'inputType' in capability ? capability.inputType : 'opaque'
    return [
      `export type ${name}Positive = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.expression)}, ${JSON.stringify(input)}>, ${capability.expectedType}>>`,
      `export type ${name}Degradation = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.degradation)}, ${JSON.stringify(input)}>, unknown[]>>`,
      `export type ${name}Composition = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.composition)}, ${JSON.stringify(input)}>, ${capability.compositionType}>>`,
    ]
  })
  .join('\n')}
`)
const assertionsOutput = new URL('../src/typed/generated/capability-assertions.types.ts', import.meta.url)
if (process.argv.includes('--check')) {
  for (const [url, expected] of [
    [output, source],
    [assertionsOutput, assertions],
  ] as const) {
    if (readFileSync(url, 'utf8') !== expected) {
      console.error(`${fileURLToPath(url)} is stale; run pnpm generate:inference-capabilities`)
      process.exitCode = 1
    }
  }
} else {
  writeFileSync(output, source)
  writeFileSync(assertionsOutput, assertions)
  console.log(`wrote ${fileURLToPath(output)}`)
  console.log(`wrote ${fileURLToPath(assertionsOutput)}`)
}

function stringifyWithUndefined(value: unknown): string {
  return JSON.stringify(value, (_key, item) => (item === undefined ? '__TYPE_LEVEL_UNDEFINED__' : item), 2).replaceAll(
    '"__TYPE_LEVEL_UNDEFINED__"',
    'undefined'
  )
}
