import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { RESOLVED_INFERENCE_CAPABILITIES } from '../src/typed/generated/capabilities.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'

const lines = [
  '// Generated by scripts/generate-inference-perf.ts. Do not edit by hand.',
  "import type { FhirpathResultIn } from '../infer.ts'",
  '',
]
let index = 0
for (const capability of Object.values(RESOLVED_INFERENCE_CAPABILITIES)) {
  index += 1
  lines.push(
    `export type Capability${String(index).padStart(3, '0')} = FhirpathResultIn<${JSON.stringify(capability.expression)}, ${JSON.stringify('input' in capability ? capability.input : 'opaque')}>`,
    `export type Composition${String(index).padStart(3, '0')} = FhirpathResultIn<${JSON.stringify(capability.composition)}, ${JSON.stringify('input' in capability ? capability.input : 'opaque')}>`
  )
}
const generated = await formatGeneratedTypeScript(`${lines.join('\n')}\n`)
const output = new URL('../src/typed/generated/full-language-perf.types.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== generated) {
    console.error(`${fileURLToPath(output)} is stale; run pnpm generate:inference-perf`)
    process.exit(1)
  }
} else {
  writeFileSync(output, generated)
  console.log(`wrote ${fileURLToPath(output)}`)
}
