import { RESOLVED_INFERENCE_CAPABILITIES } from '../src/typed/generated/capabilities.ts'
import { INFERENCE_CORPUS_AUDIT } from '../src/typed/generated/corpus-audit.ts'
import { INFERENCE_SOURCE_STEP_LIMIT, INFERENCE_TOKEN_LIMIT } from '../src/typed/inference-limits.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { writeOrCheckGenerated } from './generated-file.ts'

const lines = [
  '// Generated by scripts/generate-inference-perf.ts. Do not edit by hand.',
  "import type { FhirpathResultIn } from '../infer.ts'",
  '',
]
let index = 0
for (const capability of Object.values(RESOLVED_INFERENCE_CAPABILITIES)) {
  index += 1
  const input = 'input' in capability ? capability.input : 'inputType' in capability ? capability.inputType : 'opaque'
  const context = 'typeContext' in capability ? `, ${JSON.stringify(capability.typeContext)}` : ''
  lines.push(
    `export type Capability${String(index).padStart(3, '0')} = FhirpathResultIn<${JSON.stringify(capability.expression)}, ${JSON.stringify(input)}${context}>`,
    `export type Composition${String(index).padStart(3, '0')} = FhirpathResultIn<${JSON.stringify(capability.composition)}, ${JSON.stringify(input)}${context}>`
  )
}
const longest = INFERENCE_CORPUS_AUDIT.longestWithinBudgetCase
const tokenOverflow = INFERENCE_TOKEN_LIMIT + 1
const sourceOverflow = INFERENCE_SOURCE_STEP_LIMIT + 1
const sourceBoundary = (limit: number): string => {
  const repeated = `\${Repeat<${limit - 2}>}`
  return `export type Source${limit}Boundary = FhirpathResultIn<\`'${repeated}'\`, 'opaque'>`
}
lines.push(
  `export type LongestCorpusCase = FhirpathResultIn<${JSON.stringify(longest.expression)}, ${JSON.stringify('inputType' in longest ? longest.inputType : 'opaque')}>`,
  "type Words<Count extends number, Seen extends unknown[] = [], Result extends string = ''> = Seen['length'] extends Count ? Result : Words<Count, [...Seen, 0], Result extends '' ? 'x' : `${Result} x`>",
  "type Repeat<Count extends number, Seen extends unknown[] = [], Result extends string = ''> = Seen['length'] extends Count ? Result : Repeat<Count, [...Seen, 0], `${Result}x`>",
  `export type Token${INFERENCE_TOKEN_LIMIT}Boundary = FhirpathResultIn<Words<${INFERENCE_TOKEN_LIMIT}>, 'opaque'>`,
  `export type Token${tokenOverflow}Boundary = FhirpathResultIn<Words<${tokenOverflow}>, 'opaque'>`,
  sourceBoundary(INFERENCE_SOURCE_STEP_LIMIT),
  sourceBoundary(sourceOverflow)
)
const generated = await formatGeneratedTypeScript(`${lines.join('\n')}\n`)
const output = new URL('../src/typed/generated/full-language-perf.types.ts', import.meta.url)
writeOrCheckGenerated(output, generated, {
  check: process.argv.includes('--check'),
  regenerate: 'pnpm generate:inference-perf',
})
