import { INFERENCE_CAPABILITIES } from '../src/typed/verification/capability-registry.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { writeOrCheckGenerated } from './generated-file.ts'
import { loadInferenceInventory } from './inference-corpus.ts'

const corpus = new Map(loadInferenceInventory().map(item => [item.id, item]))
const resolved = Object.fromEntries(
  Object.entries(INFERENCE_CAPABILITIES).map(([id, capability]) => {
    const corpusCase = 'corpusId' in capability.source ? corpus.get(capability.source.corpusId) : undefined
    const expression =
      corpusCase?.expression ?? ('expression' in capability.source ? capability.source.expression : undefined)
    if (expression === undefined) {
      throw new Error(
        `${id}: corpus id ${'corpusId' in capability.source ? capability.source.corpusId : ''} does not resolve`
      )
    }
    return [
      id,
      {
        ...capability,
        expression,
        ...(corpusCase !== undefined && {
          reference: corpusCase.reference,
          ...(corpusCase.inputType !== undefined && { inputType: corpusCase.inputType }),
        }),
      },
    ]
  })
)

const serialized = Object.fromEntries(
  Object.entries(resolved).map(([id, capability]) => [
    id,
    {
      expression: capability.expression,
      degradation: capability.degradation,
      composition: capability.composition,
      analyzer: capability.analyzer,
      runtime: capability.runtime,
      ...('input' in capability && { input: capability.input }),
      ...('inputType' in capability && { inputType: capability.inputType }),
      ...('typeContext' in capability && { typeContext: capability.typeContext }),
      ...('context' in capability && { context: capability.context }),
      ...('reference' in capability && { reference: capability.reference }),
    },
  ])
)

const source =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-inference-capabilities.ts. Do not edit by hand.

export const RESOLVED_INFERENCE_CAPABILITIES = ${stringifyWithUndefined(serialized)} as const
`)
const output = new URL('../src/typed/generated/capabilities.ts', import.meta.url)
const assertions =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-inference-capabilities.ts. Do not edit by hand.

import type { HumanName, R4TypeOf, SystemQuantity } from '../../r4/generated/type-maps.ts'
import type { FhirpathResultIn } from '../infer.ts'
import type { FastSlowInferenceParity } from '../parser.ts'

type Equal<Left, Right> = (<Type>() => Type extends Left ? 1 : 2) extends <Type>() => Type extends Right ? 1 : 2
  ? true
  : false
type Assert<Condition extends true> = Condition

${Object.entries(resolved)
  .flatMap(([id, capability]) => {
    const name = id
      .split(/[^A-Za-z0-9]+/)
      .filter(Boolean)
      .map(part => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
      .join('')
    const input = 'input' in capability ? capability.input : 'inputType' in capability ? capability.inputType : 'opaque'
    const context = 'typeContext' in capability ? `, ${JSON.stringify(capability.typeContext)}` : ''
    return [
      `export type ${name}FastSlowParity = Assert<FastSlowInferenceParity<${JSON.stringify(capability.expression)}, ${JSON.stringify(input)}>>`,
      `export type ${name}Positive = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.expression)}, ${JSON.stringify(input)}${context}>, ${capability.expectedType}>>`,
      `export type ${name}Degradation = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.degradation)}, ${JSON.stringify(input)}${context}>, unknown[]>>`,
      `export type ${name}Composition = Assert<Equal<FhirpathResultIn<${JSON.stringify(capability.composition)}, ${JSON.stringify(input)}${context}>, ${capability.compositionType}>>`,
    ]
  })
  .join('\n')}
`)
const assertionsOutput = new URL('../src/typed/generated/capability-assertions.types.ts', import.meta.url)
for (const [path, content] of [
  [output, source],
  [assertionsOutput, assertions],
] as const) {
  writeOrCheckGenerated(path, content, {
    check: process.argv.includes('--check'),
    regenerate: 'pnpm generate:inference-capabilities',
  })
}

function stringifyWithUndefined(value: unknown): string {
  return JSON.stringify(value, (_key, item) => (item === undefined ? '__TYPE_LEVEL_UNDEFINED__' : item), 2).replaceAll(
    '"__TYPE_LEVEL_UNDEFINED__"',
    'undefined'
  )
}
