/**
 * Generates the R4 model data for the ModelProvider from the FHIR R4
 * StructureDefinitions shipped in @medplum/definitions (verbatim HL7 content).
 *
 * Run from packages/fhirpath: node scripts/generate-r4-model.ts
 * Output is deterministic (sorted keys), so diffs stay reviewable.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { readJson } from '@medplum/definitions'

interface ElementDefinition {
  path: string
  sliceName?: string
  max?: string
  contentReference?: string
  type?: { code: string }[]
}

interface StructureDefinition {
  id: string
  kind: 'resource' | 'complex-type' | 'primitive-type' | 'logical'
  abstract?: boolean
  baseDefinition?: string
  snapshot?: { element: ElementDefinition[] }
}

interface Bundle {
  entry: { resource: StructureDefinition }[]
}

export interface GeneratedElement {
  /** Element types; several entries for choice elements (`value[x]`). */
  t: string[]
  /** True when max cardinality is above 1. */
  a?: 1
}

export interface GeneratedType {
  /** Base type local name, absent for the roots (Base, Element). */
  b?: string
  e: Record<string, GeneratedElement>
}

const SYSTEM_TYPE_URL_PREFIX = 'http://hl7.org/fhirpath/System.'

function extract(bundles: Bundle[]): Record<string, GeneratedType> {
  const types: Record<string, GeneratedType> = {}
  for (const bundle of bundles) {
    for (const { resource: definition } of bundle.entry) {
      if (definition.kind === 'logical' || !definition.snapshot) {
        continue
      }
      const typeName = definition.id
      const base = definition.baseDefinition?.split('/').pop()
      const root: GeneratedType = { e: {} }
      if (base !== undefined && base !== typeName) {
        root.b = base
      }
      types[typeName] = root
      for (const element of definition.snapshot.element) {
        if (element.sliceName || !element.path.includes('.')) {
          continue
        }
        const separator = element.path.lastIndexOf('.')
        const ownerPath = element.path.slice(0, separator)
        let name = element.path.slice(separator + 1)
        let owner = root
        if (ownerPath !== typeName) {
          owner = types[ownerPath] ?? { b: 'BackboneElement', e: {} }
          types[ownerPath] = owner
        }
        if (name.endsWith('[x]')) {
          name = name.slice(0, -3)
        }
        const elementTypes = elementTypeNames(element)
        if (elementTypes.length === 0) {
          continue
        }
        const generated: GeneratedElement = { t: elementTypes }
        if (element.max === '*' || (element.max !== undefined && Number.parseInt(element.max, 10) > 1)) {
          generated.a = 1
        }
        owner.e[name] = generated
      }
    }
  }
  return sortKeys(types)
}

function elementTypeNames(element: ElementDefinition): string[] {
  if (element.contentReference !== undefined) {
    return [element.contentReference.replace(/^#/, '')]
  }
  const names: string[] = []
  for (const type of element.type ?? []) {
    let code = type.code
    if (code.startsWith(SYSTEM_TYPE_URL_PREFIX)) {
      code = `System.${code.slice(SYSTEM_TYPE_URL_PREFIX.length)}`
    }
    // Backbone and inline elements are identified by their path.
    if (code === 'BackboneElement' || code === 'Element') {
      code = element.path.endsWith('[x]') ? element.path.slice(0, -3) : element.path
    }
    if (!names.includes(code)) {
      names.push(code)
    }
  }
  return names
}

function sortKeys(types: Record<string, GeneratedType>): Record<string, GeneratedType> {
  const sorted: Record<string, GeneratedType> = {}
  for (const key of Object.keys(types).sort()) {
    const value = types[key] as GeneratedType
    const elements: Record<string, GeneratedElement> = {}
    for (const elementKey of Object.keys(value.e).sort()) {
      elements[elementKey] = value.e[elementKey] as GeneratedElement
    }
    sorted[key] = value.b === undefined ? { e: elements } : { b: value.b, e: elements }
  }
  return sorted
}

function emit(fileName: string, constName: string, data: Record<string, GeneratedType>, source: string): void {
  const body = JSON.stringify(data, null, 2)
  const content = `// Generated by scripts/generate-r4-model.ts from ${source} (@medplum/definitions).
// Do not edit by hand; re-run the script instead.
import type { GeneratedType } from '../model-data'

export const ${constName}: Readonly<Record<string, GeneratedType>> = ${body}
`
  const path = resolve(import.meta.dirname, '../src/r4/generated', fileName)
  writeFileSync(path, content)
  console.log(`wrote ${path} (${Object.keys(data).length} types)`)
}

const typeBundle = readJson('fhir/r4/profiles-types.json') as Bundle
const resourceBundle = readJson('fhir/r4/profiles-resources.json') as Bundle

emit('types-data.ts', 'R4_DATA_TYPES', extract([typeBundle]), 'profiles-types.json')
emit('resources-data.ts', 'R4_RESOURCES', extract([resourceBundle]), 'profiles-resources.json')
