import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { analyzeExpressionDetailed } from '../src/analyzer/analyze.ts'
import { type ArgSpec, FUNCTION_SIGNATURES, type FunctionSignature } from '../src/analyzer/signatures.ts'
import { r4Model } from '../src/r4/index.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'

const PRIMITIVE_TYPES: Readonly<Record<string, string>> = {
  'System.Boolean': 'boolean',
  'System.Integer': 'number',
  'System.Long': 'bigint',
  'System.Decimal': 'number',
  'System.String': 'string',
  'System.Date': 'string',
  'System.DateTime': 'string',
  'System.Time': 'string',
  boolean: 'boolean',
  integer: 'number',
  integer64: 'bigint',
  decimal: 'number',
  string: 'string',
  date: 'string',
  dateTime: 'string',
  instant: 'string',
  time: 'string',
}

const entries = Object.fromEntries(
  Object.entries(FUNCTION_SIGNATURES)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, signature]) => {
      const expression = functionExpression(name, signature)
      const analysis = analyzeExpressionDetailed(expression, { model: r4Model })
      const errors = analysis.diagnostics.filter(diagnostic => diagnostic.severity === 'error')
      if (errors.length > 0) {
        const details = errors.map(diagnostic => `${diagnostic.code}: ${diagnostic.message}`).join('; ')
        throw new Error(`invalid capability expression for ${name}: ${expression} (${details})`)
      }
      const analyzer = analysis.result
      return [
        `builtin.${name}`,
        {
          family: familyOf(signature),
          source: {
            expression,
            corpusGap: 'focused built-in result-rule assertion independent of surrounding corpus syntax',
          },
          expectedType: publicType(analyzer.types),
          compositionType: 'number[]',
          runtime: false,
          analyzer: {
            types: analyzer.types ?? '__TYPE_LEVEL_UNDEFINED__',
            single: analyzer.single ?? '__TYPE_LEVEL_UNDEFINED__',
          },
          degradation: 'Patient.name.unknownFn()',
          composition: `(${expression}).count()`,
        },
      ]
    })
)

const renderedEntries = JSON.stringify(entries, null, 2).replaceAll('"__TYPE_LEVEL_UNDEFINED__"', 'undefined')
const generated =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-function-capabilities.ts. Do not edit by hand.

export const BUILTIN_FUNCTION_CAPABILITIES = ${renderedEntries} as const
`)
const output = new URL('../src/typed/generated/function-capabilities.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== generated) {
    console.error(`${fileURLToPath(output)} is stale; run pnpm generate:function-capabilities`)
    process.exit(1)
  }
} else {
  writeFileSync(output, generated)
  console.log(`wrote ${fileURLToPath(output)}`)
}

function familyOf(signature: FunctionSignature): 'function-fixed' | 'function-input' | 'function-lambda' {
  if (
    signature.args?.some(argument => argument === 'expression' || argument === 'condition' || argument === 'sort-key')
  ) {
    return 'function-lambda'
  }
  return signature.result.kind === 'input' || signature.result.kind === 'input-item'
    ? 'function-input'
    : 'function-fixed'
}

function functionExpression(name: string, signature: FunctionSignature): string {
  switch (name) {
    case 'resolve':
      return 'Patient.generalPractitioner.resolve()'
    case 'ofType':
      return `Patient.name.${name}(HumanName)`
    case 'as':
      return 'Patient.name.first().as(HumanName)'
    case 'select':
      return 'Patient.name.select(given)'
    case 'iif':
      return 'Patient.name.iif(true, given, family)'
    case 'coalesce':
      return 'Patient.name.coalesce(given, family)'
    case 'union':
    case 'combine':
      return `Patient.name.${name}(Patient.name)`
    case 'defineVariable':
      return "Patient.name.defineVariable('generatedVariable')"
    case 'aggregate':
      return 'Patient.name.aggregate($total | $this, {})'
    default:
      break
  }
  const focus = focusFor(signature)
  const args = (signature.args ?? []).map(argumentFor)
  return `${focus}.${name}(${args.join(', ')})`
}

function focusFor(signature: FunctionSignature): string {
  switch (signature.input?.kind) {
    case 'String':
      return "'abc'"
    case 'Boolean':
      return 'true'
    case 'Numeric':
      return '2'
    case 'Quantity':
      return "1 'mg'"
    case 'Temporal':
      return '@2020-01-01'
    default:
      return signature.input?.singleton === true ? 'Patient.name.first()' : 'Patient.name'
  }
}

function argumentFor(argument: ArgSpec): string {
  switch (argument) {
    case 'condition':
      return 'true'
    case 'expression':
    case 'sort-key':
      return '$this'
    case 'type-name':
      return 'HumanName'
    case 'String':
      return "'x'"
    case 'Boolean':
      return 'true'
    case 'Numeric':
      return '1'
    case 'Quantity':
      return "1 'mg'"
    case 'Temporal':
      return '@2020-01-01'
    case 'any':
      return "'x'"
  }
}

function publicType(types: string[] | undefined): string {
  if (types === undefined) return 'unknown[]'
  if (types.length === 0) return 'never[]'
  const members = [
    ...new Set(types.map(type => type.replace(/^FHIR\./, '')).map(type => PRIMITIVE_TYPES[type] ?? type)),
  ]
  if (
    members.every(member => member === 'boolean' || member === 'number' || member === 'bigint' || member === 'string')
  ) {
    return `(${members.join(' | ')})[]`.replace(/^\(([^|()]+)\)\[\]$/, '$1[]')
  }
  return `R4TypeOf[${members.map(member => JSON.stringify(member)).join(' | ')}][]`
}
