import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { INFERENCE_CAPABILITIES } from '../src/typed/capability-registry.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { loadInferenceInventory } from './inference-corpus.ts'

const corpus = new Map(loadInferenceInventory().map(item => [item.id, item]))
const resolved = Object.fromEntries(
  Object.entries(INFERENCE_CAPABILITIES).map(([id, capability]) => {
    const corpusCase = 'corpusId' in capability.source ? corpus.get(capability.source.corpusId) : undefined
    const expression =
      corpusCase?.expression ?? ('expression' in capability.source ? capability.source.expression : undefined)
    if (expression === undefined) {
      throw new Error(
        `${id}: corpus id ${'corpusId' in capability.source ? capability.source.corpusId : ''} does not resolve`
      )
    }
    return [
      id,
      {
        ...capability,
        expression,
        ...(corpusCase !== undefined && {
          reference: corpusCase.reference,
          ...(corpusCase.inputType !== undefined && { inputType: corpusCase.inputType }),
        }),
      },
    ]
  })
)

const source =
  await formatGeneratedTypeScript(`// Generated by scripts/generate-inference-capabilities.ts. Do not edit by hand.

export const RESOLVED_INFERENCE_CAPABILITIES = ${JSON.stringify(resolved, null, 2)} as const
`)
const output = new URL('../src/typed/generated/capabilities.ts', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== source) {
    console.error(`${fileURLToPath(output)} is stale; run pnpm generate:inference-capabilities`)
    process.exit(1)
  }
} else {
  writeFileSync(output, source)
  console.log(`wrote ${fileURLToPath(output)}`)
}
