import {
  OPERATOR_RESULT_RULES,
  type OperatorResultRule,
  TYPE_OPERATOR_RESULT_RULES,
} from '../src/analyzer/operator-rules.ts'
import { type ArgSpec, FUNCTION_SIGNATURES, type ResultRule } from '../src/analyzer/signatures.ts'
import { CALENDAR_DURATION_UNITS } from '../src/lexer/tokens.ts'
import { INFIX_PARSELETS, PREFIX_PARSELETS } from '../src/parser/precedence.ts'
import { R4_RESOURCES } from '../src/r4/generated/resources-data.ts'
import { R4_DATA_TYPES } from '../src/r4/generated/types-data.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'
import { writeOrCheckGenerated } from './generated-file.ts'

const compactOutputUrl = new URL('../src/typed/metadata-compact.ts', import.meta.url)
const MAX_FAST_RESOURCE_ROOT_LENGTH = 33
const MAX_FAST_ELEMENT_NAME_LENGTH = 33
const MAX_FAST_FUNCTION_NAME_LENGTH = 18

assertMaxLength(
  'R4 element',
  Object.values({ ...R4_DATA_TYPES, ...R4_RESOURCES }).flatMap(type => Object.keys(type.e)),
  MAX_FAST_ELEMENT_NAME_LENGTH
)
assertMaxLength(
  'R4 resource root',
  Object.keys(R4_RESOURCES).filter(name => !name.includes('.')),
  MAX_FAST_RESOURCE_ROOT_LENGTH
)
assertMaxLength('function', Object.keys(FUNCTION_SIGNATURES), MAX_FAST_FUNCTION_NAME_LENGTH)

function assertMaxLength(label: string, names: string[], limit: number): void {
  const oversized = names.filter(name => name.length > limit)
  if (oversized.length > 0) {
    throw new Error(`${label} names exceed the fast-parser source proof (${limit}): ${oversized.join(', ')}`)
  }
}

function compactGeneratedSource(): string {
  return `// Generated by scripts/generate-type-metadata.ts. Do not edit by hand.

export interface CompactFunctionRules {
${Object.entries(FUNCTION_SIGNATURES)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, signature]) => `  ${JSON.stringify(name)}: ${compactResultRuleType(signature.result)}`)
  .join('\n')}
}

export interface CompactFunctionArguments {
${Object.entries(FUNCTION_SIGNATURES)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, signature]) => `  ${JSON.stringify(name)}: ${compactArgumentSpecsType(signature.args ?? [])}`)
  .join('\n')}
}

export type CompactLambdaArgument0Name = ${lambdaArgumentNames(0)}
export type CompactLambdaArgument1Name = ${lambdaArgumentNames(1)}
export type CompactLambdaArgument2Name = ${lambdaArgumentNames(2)}

export type CompactFastFunctionName = ${Object.entries(FUNCTION_SIGNATURES)
    .filter(([name, signature]) => name !== 'defineVariable' && isFastResultRule(signature.result))
    .map(([name]) => JSON.stringify(name))
    .join(' | ')}

export interface CompactOperatorRules {
${Object.entries(OPERATOR_RESULT_RULES)
  .map(([operator, rule]) => `  ${JSON.stringify(operator)}: ${compactOperatorRuleType(rule)}`)
  .join('\n')}
}

export interface CompactTypeOperatorRules {
${Object.entries(TYPE_OPERATOR_RESULT_RULES)
  .map(([operator, rule]) => `  ${JSON.stringify(operator)}: ${compactOperatorRuleType(rule)}`)
  .join('\n')}
}

export interface CompactPrefixParselets {
${Object.entries(PREFIX_PARSELETS)
  .map(
    ([token, record]) =>
      `  ${JSON.stringify(token)}: readonly [${[
        record.tokenKind,
        record.fixity,
        record.bindingPower,
        record.associativity,
        record.rhs,
        record.reducer,
      ]
        .map(value => JSON.stringify(value))
        .join(', ')}]`
  )
  .join('\n')}
}

export interface CompactInfixParselets {
${Object.entries(INFIX_PARSELETS)
  .map(
    ([token, record]) =>
      `  ${JSON.stringify(token)}: readonly [${[
        record.tokenKind,
        record.fixity,
        record.bindingPower,
        record.associativity,
        record.rhs,
        record.reducer,
      ]
        .map(value => JSON.stringify(value))
        .join(', ')}]`
  )
  .join('\n')}
}

export type CompactCalendarUnit = ${[...CALENDAR_DURATION_UNITS]
    .sort()
    .map(unit => JSON.stringify(unit))
    .join(' | ')}
`
}

function compactArgumentSpecsType(args: readonly ArgSpec[]): string {
  return `readonly [${args.map(argument => JSON.stringify(argument)).join(', ')}]`
}

function lambdaArgumentNames(index: number): string {
  const names = Object.entries(FUNCTION_SIGNATURES)
    .filter(([, signature]) => {
      const args = signature.args ?? []
      const argument = args[index] ?? args.at(-1)
      return argument === 'expression' || argument === 'condition' || argument === 'sort-key'
    })
    .map(([name]) => JSON.stringify(name))

  return names.length > 0 ? names.join(' | ') : 'never'
}

function isFastResultRule(rule: ResultRule): boolean {
  return ['fixed', 'input', 'input-item'].includes(rule.kind)
}

function compactResultRuleType(rule: ResultRule): string {
  switch (rule.kind) {
    case 'fixed':
      return `readonly ['fixed', ${rule.types?.map(type => JSON.stringify(type)).join(' | ') ?? 'never'}]`
    case 'input':
      return "readonly ['input']"
    case 'input-item':
      // The type-level state tracks value types, not analyzer cardinality.
      return "readonly ['input']"
    case 'argument':
      return `readonly ['argument', ${rule.index}]`
    case 'union':
      return `readonly ['union', ${rule.sources.map(source => JSON.stringify(source)).join(' | ')}]`
    case 'arguments-union':
      return "readonly ['arguments-union']"
    case 'reference-targets':
      return "readonly ['reference-targets']"
    case 'unknown':
      return "readonly ['unknown']"
  }
}

function compactOperatorRuleType(rule: OperatorResultRule): string {
  switch (rule.kind) {
    case 'fixed':
      return `readonly ['fixed', ${rule.types.map(type => JSON.stringify(type)).join(' | ')}]`
    case 'arithmetic':
      return "readonly ['arithmetic']"
    case 'union':
      return "readonly ['union']"
    case 'narrow':
      return "readonly ['narrow']"
  }
}

const compactNext = await formatGeneratedTypeScript(compactGeneratedSource())
writeOrCheckGenerated(compactOutputUrl, compactNext, {
  check: process.argv.includes('--check'),
  regenerate: 'pnpm generate:type-metadata',
})
