import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { OPERATOR_RESULT_RULES, TYPE_OPERATOR_RESULT_RULES } from '../src/analyzer/operator-rules.ts'
import { FUNCTION_SIGNATURES } from '../src/analyzer/signatures.ts'
import { INFIX_PARSELETS, PREFIX_PARSELETS } from '../src/parser/precedence.ts'
import { formatGeneratedTypeScript } from './format-generated.ts'

const outputUrl = new URL('../src/typed/generated/metadata.ts', import.meta.url)

function generatedSource(): string {
  const functionRules = Object.fromEntries(
    Object.entries(FUNCTION_SIGNATURES)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, signature]) => [name, signature.result])
  )
  return `// Generated by scripts/generate-type-metadata.ts. Do not edit by hand.

export const TYPE_FUNCTION_RULES = ${JSON.stringify(functionRules, null, 2)} as const

export const TYPE_OPERATOR_RULES = ${JSON.stringify(OPERATOR_RESULT_RULES, null, 2)} as const

export const TYPE_TYPE_OPERATOR_RULES = ${JSON.stringify(TYPE_OPERATOR_RESULT_RULES, null, 2)} as const

export const TYPE_PREFIX_PARSELETS = ${JSON.stringify(PREFIX_PARSELETS, null, 2)} as const

export const TYPE_INFIX_PARSELETS = ${JSON.stringify(INFIX_PARSELETS, null, 2)} as const
`
}

const next = await formatGeneratedTypeScript(generatedSource())
if (process.argv.includes('--check')) {
  const path = fileURLToPath(outputUrl)
  const current = readFileSync(path, 'utf8')
  if (current !== next) {
    console.error(`${path} is stale; run pnpm generate:type-metadata`)
    process.exit(1)
  }
} else {
  writeFileSync(outputUrl, next)
  console.log(`wrote ${fileURLToPath(outputUrl)}`)
}
