// Generated by dts-bundle-generator v9.5.1

interface ElementInfo {
	/** Canonical type name(s); more than one for choice elements like `Observation.value[x]`. */
	types: string[];
	isCollection: boolean;
	/** True for `[x]` elements, whose JSON keys carry a type suffix (`valueQuantity`). */
	isChoice: boolean;
	/**
	 * Resource type names a Reference-typed element may point to, from
	 * `Reference.targetProfile` — what resolve() statically yields. Absent when
	 * the element is not a reference or the reference is unconstrained.
	 */
	referenceTargets?: string[];
}
interface ModelProvider {
	/** Namespace prefix for the model's types, e.g. `FHIR`. */
	namespace: string;
	/** Resolve an unqualified type name to its canonical name, or undefined if unknown. */
	resolveType(name: string): string | undefined;
	/** Look up an element on a type, resolving choice elements by their stem name. */
	getElement(type: string, element: string): ElementInfo | undefined;
	/** True when `type` equals or derives from `base` (both canonical). */
	isSubtypeOf(type: string, base: string): boolean;
	/**
	 * All element names of a type, own and inherited, in declaration order.
	 * Undefined when the type is unknown to the model — navigation then falls back
	 * to raw JSON reads instead of strict unknown-element errors.
	 */
	listElements?(type: string): string[] | undefined;
}
interface SourceSpan {
	/** 0-based offset of the first character. */
	start: number;
	/** 0-based offset one past the last character. */
	end: number;
	/** 1-based line of the first character. */
	line: number;
	/** 1-based column of the first character. */
	column: number;
}
type ValueKind = "Boolean" | "String" | "Numeric" | "Temporal" | "Quantity" | "Complex";
type ValueArgSpec = "any" | ValueKind;
interface CustomFunctionSignature {
	input?: {
		kind?: ValueKind;
		singleton?: boolean;
	};
	args?: ValueArgSpec[];
	result?: {
		types?: string[];
		single?: boolean;
	};
}
interface LocalModuleOptions {
	/** Import-source prefixes that are the FHIRPath API. Defaults to `['fhirpath-ts']`. */
	packages?: readonly string[];
	/**
	 * Also treat relative imports (`./`, `../`) as the FHIRPath API. Off by default
	 * (a consumer's relative `compile` is not FHIRPath); turn it on so the package
	 * can dogfood the rule on its own source, which imports its API relatively.
	 */
	localImports?: boolean;
}
export interface LexicalExpressionSite {
	expression: string;
	/** 0-based offset of the expression's first character in the source text. */
	start: number;
}
/**
 * Find the FHIRPath expression literals in `sourceText`: `` fhirpath`...` `` tags
 * plus the literal expression arguments of the calls in `CALL_SITES`, including
 * the ones nested in `project()` columns and `checkConstraints()` constraints.
 * `options` widens which import sources count as the real FHIRPath API.
 */
export declare function findLexicalExpressionSites(sourceText: string, options?: LocalModuleOptions): LexicalExpressionSite[];
export interface AnalyzerDiagnostic {
	severity: "error" | "warning";
	/** Stable rule identifier, e.g. `unknown-element` or `singleton-required`. */
	code: string;
	message: string;
	span: SourceSpan;
}
/**
 * A host-supplied variable declared to the analyzer (HAPI's
 * resolveConstantType): the host will pass it at evaluation via
 * EvaluateOptions.env, so `%name` is not an unknown-variable error. Types are
 * optional — an untyped declaration stays an unknown region.
 */
export interface DeclaredVariable {
	/** Candidate type names ('Patient', 'System.String'); omit to leave the type unknown. */
	types?: string[];
	/** True when the variable always holds at most one item. */
	single?: boolean;
}
/**
 * A host-supplied function declared to the analyzer (HAPI's resolveFunction +
 * checkFunction): the name and arities resolve calls, and the optional
 * signature type-checks them. A CustomFunction (EvaluateOptions.functions)
 * satisfies this shape, so the same record can be passed to both.
 */
export interface DeclaredFunction {
	minArity?: number;
	maxArity?: number;
	signature?: CustomFunctionSignature;
}
export interface AnalyzeOptions {
	model?: ModelProvider;
	/** Canonical type of the input the expression will run against, e.g. `FHIR.Patient` or `Patient`. */
	inputType?: string;
	/** Host-supplied functions by name — EvaluateOptions.functions can be passed as-is. */
	functions?: Record<string, DeclaredFunction>;
	/** Host-supplied environment variables by name (with or without the leading `%`). */
	variables?: Record<string, DeclaredVariable>;
}
export interface AnalysisDetails {
	diagnostics: AnalyzerDiagnostic[];
	/**
	 * `Type.element` paths the expression reads (local type names), deduped in
	 * first-visit order — HAPI's `elementDependencies`. Lets callers know which
	 * elements an expression depends on, e.g. for change tracking or editors.
	 */
	elementDependencies: string[];
}
/**
 * Statically check one expression against the model: spec §11's strict-mode rules
 * (singleton misuse, wrong operand and argument types, incomparable equality)
 * plus unknown elements, functions, arities, type names, and variables.
 */
export declare function analyzeExpression(expression: string, options?: AnalyzeOptions): AnalyzerDiagnostic[];
/** `analyzeExpression` plus the element paths the expression touches. */
export declare function analyzeExpressionDetailed(expression: string, options?: AnalyzeOptions): AnalysisDetails;

export {};
