// Generated by dts-bundle-generator v9.5.1

interface SourceSpan {
	/** 0-based offset of the first character. */
	start: number;
	/** 0-based offset one past the last character. */
	end: number;
	/** 1-based line of the first character. */
	line: number;
	/** 1-based column of the first character. */
	column: number;
}
interface ElementInfo {
	/** Canonical type name(s); more than one for choice elements like `Observation.value[x]`. */
	types: string[];
	isCollection: boolean;
	/** True for `[x]` elements, whose JSON keys carry a type suffix (`valueQuantity`). */
	isChoice: boolean;
}
interface ModelProvider {
	/** Namespace prefix for the model's types, e.g. `FHIR`. */
	namespace: string;
	/** Resolve an unqualified type name to its canonical name, or undefined if unknown. */
	resolveType(name: string): string | undefined;
	/** Look up an element on a type, resolving choice elements by their stem name. */
	getElement(type: string, element: string): ElementInfo | undefined;
	/** True when `type` equals or derives from `base` (both canonical). */
	isSubtypeOf(type: string, base: string): boolean;
	/**
	 * All element names of a type, own and inherited, in declaration order.
	 * Undefined when the type is unknown to the model — navigation then falls back
	 * to raw JSON reads instead of strict unknown-element errors.
	 */
	listElements?(type: string): string[] | undefined;
}
export interface AnalyzerDiagnostic {
	severity: "error" | "warning";
	/** Stable rule identifier, e.g. `unknown-element` or `singleton-required`. */
	code: string;
	message: string;
	span: SourceSpan;
}
export interface AnalyzeOptions {
	model?: ModelProvider;
	/** Canonical type of the input the expression will run against, e.g. `FHIR.Patient` or `Patient`. */
	inputType?: string;
}
/**
 * Statically check one expression against the model: spec §11's strict-mode rules
 * (singleton misuse, wrong operand and argument types, incomparable equality)
 * plus unknown elements, functions, arities, and type names.
 */
export declare function analyzeExpression(expression: string, options?: AnalyzeOptions): AnalyzerDiagnostic[];

export {};
